In [7]:
 import numpy as np

**Basic Array creation**

In [8]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a=[1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [10]:
np.array(a) #shows dtype u32 which means all data types have been converted to unicode /strings 

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [11]:
a=[1,2,3] #same data type then not converted to string
a

[1, 2, 3]

In [12]:
np.array(a)

array([1, 2, 3])

In [13]:
l=[[1,2,3],[4,5,6],[7,8,9]] #list doesnt support multidimensional
l#o/p looks like 1 dimensional

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)#now it looks like 2 dimensional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array generation function**

In [15]:
arr=np.arange(1,11,2) #generate array in range w step
arr

array([1, 3, 5, 7, 9])

In [16]:
arr=np.zeros(6) #array of 0s
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
arr=np.zeros((4,8))#in matrix form
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr=np.ones((3,4))#array of ones
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
arr=np.linspace(1,5,3) #shift+tab to see what it does-> this function start,stop,no of numbers 
arr

array([1., 3., 5.])

**Random Generation function**

In [31]:
np.random.rand(10) #random library bata rand func call 1 bracket bho bhane vector 2 ta bracket bho bhane matrix 
#you see all values b/w 0 and 1 due to concept of normalization 

array([0.46065304, 0.20872901, 0.90528477, 0.17092317, 0.71744227,
       0.76498445, 0.01352112, 0.95762943, 0.26536528, 0.04249118])

In [33]:
np.random.randn(10)#concept of standardization ->which has values from -3 to 3 

array([ 0.81279917, -1.75507663, -0.25583445, -0.78770282,  0.00358014,
       -1.3676406 ,  0.65733772,  2.14930455, -1.74535851,  1.07719602])

In [39]:
np.random.randint(6,10,3)#generates random NUMBER low,high,size ->check w shift+tab

array([8, 6, 9])

**Array Attributes**

In [41]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.shape #attribute ma chai call gardaina direct lekhcha method lai chai call garcha with ()

(3, 3)

In [43]:
arr.size

9

In [45]:
arr.dtype #datatype 

dtype('int32')

**Array Methods**

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr.min()

1

In [48]:
arr.max()

9

In [49]:
arr.sum() 

45

In [52]:
np.sum(arr,axis=1) #np.sum has arr,axis ->vertical axis =0 horizontal axis =1

array([ 6, 15, 24])

In [53]:
arr.mean()

5.0

In [54]:
arr.std()

2.581988897471611

In [55]:
arr.argmax()#means maximum element ko index k ho

8

In [56]:
arr.argmin()

0

**Reshaping and resizing**

In [58]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [61]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])