In [5]:
import numpy as np

**NUMPY INDEXING AND SLICING OF VECTORS**

In [7]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[6]

17

In [16]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

**NUMPY INDEXING AND SLICING OF MATRIX**

In [20]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
arr[1]#1st element will target rows 

array([ 6,  7,  8,  9, 10])

In [24]:
arr[0,4]#0th row 4th col

5

In [28]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [31]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [33]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**BOOLEAN INDEXING**

In [35]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
bool_index= arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [37]:
arr[bool_index]


array([12, 14, 16, 18, 20])