In [1]:
import numpy as np

**Array operations**

*Arthimentic operations*


In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [3]:
arr2=a1+a2 #respective indexes added but the shape should be same
arr2

array([ 7,  9, 11, 13, 15])

In [4]:
a1-a2

array([-5, -5, -5, -5, -5])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1//a2

array([0, 0, 0, 0, 0])

In [8]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

*Broadcasting*

In [9]:
l=[10,20,30,40]
arr=np.array(l)

In [11]:
#l+1 error so to avoid this use array 
for i in l:
    print(i+1)

11
21
31
41


In [13]:
arr=np.array(l)
arr+1

array([11, 21, 31, 41])

In [16]:
arr2=np.arange(1,26).reshape(5,5) #these also work in matrix not only in vector
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
arr2 #changes apply to all cells above and below

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr2+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [19]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

*Deep and shallow copy*

In [39]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
slice=a[:5]
slice=slice*10
slice #if u take a portion from the array then changes in that slice isnt refletced in orginal array->concept is called shallow copy

array([990,  20,  30,  40,  50])

In [44]:
a#but no change in list but changes made in list is reflected 

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
a
b=a
b[0]=99 #now changes in b are also reflected in a concept is called deep copy
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
#to create shallow copy here we use .copy 
b=a.copy()
b[1]=99
b

array([99, 99,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
a #no change in a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

*Matrix Operations*

In [51]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


In [52]:
A @ B #matrix multiplication is done using this ->@

array([[19, 22],
       [43, 50]])

In [53]:
#another way is np.dot(arg)
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [54]:
A.T #to transpose .T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

Stacking Array

In [55]:
A

array([[1, 2],
       [3, 4]])

In [56]:
B

array([[5, 6],
       [7, 8]])

In [58]:
#u cannot stack two matrixes but u can stack vectors 2 types of stack vertical horizontal 

In [60]:
a=np.arange(1,5)
b=np.arange(6,10)

In [61]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [62]:
np.hstack((a,b)) #this makes it a 1d array/vector to avoid that we se column_stack

array([1, 2, 3, 4, 6, 7, 8, 9])

In [63]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

Splitting Array

In [ ]:
#split two types ->horizontal or vertical

In [66]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
np.hsplit(c,2) #splits it vertically but has to be in equal division

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [71]:
np.vsplit(c,2)#splits horizontally

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]