In [272]:
import numpy as np

**Valid Sudoku**

In [273]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [274]:
b=np.sum(s,axis=1) #vertical axis =0, horizontal axis =1
for i in b:
    if i!=45:
        print("sudoku is not valid")
else:
        print("sudoku is valid")

sudoku is valid


In [275]:
c=np.sum(s,axis=0)
for i in c:
    if i!=45:
        print("sudoku is not valid")
else:
        print("sudoku is valid")


sudoku is valid


In [276]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [277]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [278]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [279]:
flag=1
for i in range(0,9,3):
    for j in range(0,9,3):
        block=s[i:i+3,j:j+3]
        if (np.sum(block)!=45):
            flag=0 
            break
if flag==0:
    print("invalid sudoku")
else:
    print("valid sudoku")
    

valid sudoku


**General Questions**

In [280]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [281]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [282]:
#Find the average age of students.
ageSlice=data[:,0]
ageSlice

array([18, 19, 17, 18, 20])

In [283]:
np.mean(ageSlice)

18.4

In [284]:
#Extract Math marks of all students.
MathMarks=data[:,1]
MathMarks


array([85, 92, 76, 65, 90])

In [285]:
#Find the highest Science mark.
ScienceMarks=data[:,2]
ScienceMarks
ans=ScienceMarks[np.argmax(ScienceMarks)]
ans

95

In [286]:
#Get details of the student who scored more than 90 in Math.
data[MathMarks>90]


array([[19, 92, 88]])

In [287]:
#Increase Math marks of all students by 5.
data[:,1]=data[:,1]+5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [288]:
#Find how many students are younger than 19.
ageSlice

array([18, 19, 17, 18, 20])

In [289]:
number=ageSlice[ageSlice>19]

In [290]:
len(number)

1

In [291]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [292]:
#Get data of students who scored at least 80 in both subjects.
data[(MathMarks>=80) & (ScienceMarks>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [304]:
#Replace all Science marks < 75 with 0.
data[data[:,2]<75,2]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])