In [1]:
 import numpy as np

**Basic Array creation**

In [5]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a=[1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [10]:
np.array(a) #shows dtype u32 which means all data types have been converted to unicode /strings 

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [11]:
a=[1,2,3] #same data type then not converted to string
a

[1, 2, 3]

In [12]:
np.array(a)

array([1, 2, 3])

In [14]:
l=[[1,2,3],[4,5,6],[7,8,9]] #list doesnt support multidimensional
l#o/p looks like 1 dimensional

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(l)#now it looks like 2 dimensional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

*Array generation function*

In [16]:
arr=np.arange(1,11,2) #generate array in range w step
arr

array([1, 3, 5, 7, 9])

In [17]:
arr=np.zeros(6) #array of 0s
arr

array([0., 0., 0., 0., 0., 0.])

In [20]:
arr=np.zeros((4,8))#in matrix form
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr=np.ones((3,4))#array of ones
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])